apiVersion: v1
kind: Service
metadata:
  name: rag
  annotations:
    zarf.dev/connect-description: "Load the spec for the RAG API"
    zarf.dev/connect-url: "/docs"
  labels:
    zarf.dev/connect-name: lfai-rag
spec:
  selector:
    app: rag
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP