name: pytest
on: 
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version-file: 'pyproject.toml'
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - run: cp .env.example .env
      - run: make requirements-dev
      - run: make test